const dummyData = [
  {
    _id: "1",
    userId: "user_001",
    name: "Alice Johnson",
    timestampDateAndTime: new Date().toISOString(),
    timestamp: Date.now(),
    query: [
      {
        _id: "q_101",
        name: "Alice Johnson",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "How can I reset my password?",
        role: "USER",
      },
      {
        _id: "q_102",
        name: "Support Agent",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "You can reset your password in the settings.",
        role: "ADMIN",
      },
    ],
  },
  {
    _id: "2",
    userId: "user_002",
    name: "Bob Smith",
    timestampDateAndTime: new Date().toISOString(),
    timestamp: Date.now(),
    query: [
      {
        _id: "q_201",
        name: "Bob Smith",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "I need help with my account activation.",
        role: "USER",
      },
      {
        _id: "q_202",
        name: "Support Agent",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "Please check your email for the activation link.",
        role: "ADMIN",
      },
      {
        _id: "q_203",
        name: "Bob Smith",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "I haven't received any email.",
        role: "USER",
      },
    ],
  },
  {
    _id: "3",
    userId: "user_003",
    name: "Charlie Adams",
    timestampDateAndTime: new Date().toISOString(),
    timestamp: Date.now(),
    query: [
      {
        _id: "q_301",
        name: "Charlie Adams",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "Is there a way to export my data?",
        role: "USER",
      },
      {
        _id: "q_302",
        name: "Support Agent",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message:
          "Yes, you can find the export option in your account settings.",
        role: "ADMIN",
      },
      {
        _id: "q_303",
        name: "Charlie Adams",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "Thanks! That helped.",
        role: "USER",
      },
    ],
  },
  {
    _id: "4",
    userId: "user_004",
    name: "Diana Patel",
    timestampDateAndTime: new Date().toISOString(),
    timestamp: Date.now(),
    query: [
      {
        _id: "q_401",
        name: "Diana Patel",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "How can I delete my account?",
        role: "USER",
      },
      {
        _id: "q_402",
        name: "Support Agent",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "To delete your account, please contact our support team.",
        role: "ADMIN",
      },
    ],
  },
  {
    _id: "5",
    userId: "user_005",
    name: "Ethan Brown",
    timestampDateAndTime: new Date().toISOString(),
    timestamp: Date.now(),
    query: [
      {
        _id: "q_501",
        name: "Ethan Brown",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "Can I change my email address?",
        role: "USER",
      },
      {
        _id: "q_502",
        name: "Support Agent",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "Yes, you can update your email in profile settings.",
        role: "ADMIN",
      },
      {
        _id: "q_503",
        name: "Ethan Brown",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "Got it! Thanks.",
        role: "USER",
      },
      {
        _id: "q_504",
        name: "Support Agent",
        timestampDateAndTime: new Date().toISOString(),
        timestamp: Date.now(),
        message: "You're welcome! Let us know if you need more help.",
        role: "ADMIN",
      },
    ],
  },
];

export default dummyData;
